openapi: 3.0.0
info:
  title: Movie API
  version: 1.0.0
paths:
  /api/movies:
    get:
      summary: Get all movies
      responses:
        '200':
          description: A list of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
    post:
      summary: Create a new movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '201':
          description: The created movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /api/movies/{id}:
    get:
      summary: Get a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Movie not found
    patch:
      summary: Update a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '200':
          description: The updated movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Movie not found
    delete:
      summary: Delete a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Movie deleted successfully
        '404':
          description: Movie not found
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          example: "Inception"
        director:
          type: string
          example: "Christopher Nolan"
        synopsis:
          type: string
          example: "A thief who steals corporate secrets through the use of dream-sharing technology..."
        releaseYear:
          type: string
          example: "2010"
      required:
        - id
        - title
        - director
